### ISSUE TITLE
multipane

### ISSUE THREAD

**Issue by Erikkre** [OpenLiberty/guide-jpa-intro#91]
### Defining a JPA entity class
- [ ] right side of annotations chart cut off, could use some formatting (maybe make middle guide panel larger?)
### Configuring JPA
- [x] transaction-type="JTA" should be set up as a hotspot

### Checklist for Review
**Through the browser:**
- [x] Read over guide and run through all commands (copy and paste using browser etc..)
- [x] Test the actual application (use it, hit endpoints, etc.)
- [x] No files in the middle panel (guide section)
- [x] Appropriate files are being displayed on the right hand side at the right time
- [x] Any mention of code in the right panel should be hot spotted
- [x] Make sure hotspots actually point to the correct lines
- [x] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [x] All code commands are highlighting the right code
- [x] Any actions to look at the code should be a hotspot
- [x] Guide attribution is present
- [x] Any links are hyperlinks with the webpage title not the URL
- [x] Feature versions should not be included in the guide
**In the README.adoc:**
- [x] Tags in the front matter are correct (MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE)
    - [x] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [x] Failsafe plugin and Surefire plugin updates if applicable
- [x] Parent POM update
    - [x] start directory
    - [x] finish directory
- [x] Files are formatted correctly
- [x] .travis.yaml file is updated accordingly

In the readme.adoc's page tags make sure to add another ' to the [Java EE']

**Comment by justineechen** [comment]
### Checklist for Post-Review
**Through the browser:**
- [ ] Read through guide, making sure that the flow of the guide is good
- [ ] Click all links to make sure they lead to the correct place
- [ ] Make sure hotspots, code_commands and files are correct
- [ ] Run Acrolinx
