### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-jpa-intro#94]
**Configuring JPA**
- [x] "The `name` attribute is required and is used to identify the persistent unit.." -> `name` should be hotspotted and highlight the name attribute
- [x] "The data source has already been configured for you in the `backendServices/src/main/liberty/config/server.xml` file." -> In the `server.xml` hotspot, could we highlight the data source configuration when jumping to the file? I think that would be more beneficial to the user than just switching to the file itself, this way they know exactly where the configuration is taking place.
- [x] "JPA Extensions Reference for EclipseLink." hyperlink doesn't open in new tab

**Performing CRUD**
- [x] "The CRUD operations are defined in the DAO. To perform these operations by using JPA," -> This sentence is then followed by a code command arrow. Is this valid? I have not seen something like this in previous guides. Perhaps we should make this a full sentence instead.
- [x] "The DAO is injected into the `finish/backendServices/src/main/java/io/openliberty/guides/event/resources/EventResource.java` class and used to access and persist data." -> `finish` directory can be taken off the path

**Building and running the application**
- [ ] "Your Maven `pom.xml` is already configured to start the application in this server instance." -> Should `pom.xml` be hotspotted and displayed in the right hand pane?

**Nice work you did it!**
- [x] "You learned how to map Java objects to database tables by defining a JPA entity class whose instances are represented as rows in the table in Open Liberty" -> Makes it sounds like the table is in Open Liberty. I think this sentence should be reworded or perhaps the "in Open Liberty" should be added elsewhere.

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-jpa-intro/commit/f1bc263982bdcca99f8dda0a996e2716d2270bed

**Comment by justineechen** [comment]
I don't think it's necessary to add the pom.xml because we aren't really going into anything about the file and it doesn't help the user learn about JPA.
