### ISSUE TITLE
The jpa guide does not show up in search results

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/guide-jpa-intro#96]
When I search for the "jpa" on the open liberty website this guide does not appear.   

<img width="1096" alt="Screen Shot 2019-04-08 at 11 54 42 AM" src="https://user-images.githubusercontent.com/26146482/55738587-63ef5680-59f5-11e9-9c5f-462ca80952b8.png">

However, it does appear when I search "java persistence".  A developer may not know what jpa stands for and may simply search "jpa".

**Comment by yeekangc** [comment]
https://github.com/OpenLiberty/guide-jpa-intro/pull/97

**Comment by gkwan-ibm** [comment]
#98
